version: "3.5"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /srv/qbittorrent:/config
      - /torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /vw-data:/data
    ports:
    - 8001:80
  jellyfin:
    iamge: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    volumes:
      - /srv/jellyfin:/config
      - /srv/jellyfin:/cache
      - /media/films:/films
      - /media/tvshows:/tvshows
    restart: unless-stopped
  portainer-agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: 'portainer/agent:2.19.1'


    